import NewNavbar from "@/app/components/NewNavbar";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DMM : Home",
  description: "Generated by create next app",
};

export default function Home({ children }) {
  return (
    <div>
      <div>
        <NewNavbar />
        {children}
      </div>
    </div>
  );
}
