import CustomNavbar from "@/components/CustomNavbar";
import Footer from "@/components/Footer";
import Logobar from "@/components/Logobar";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`backdrop-blur-md ${inter.className} bg-slate-300 w-full md:w-10/12 m-auto `}
      >
        <Logobar />
        <CustomNavbar />
        {children}
        <Footer />
        <script src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"></script>
      </body>
      
    </html>
  );
}
