import CustomNavbar from "@/app/components/CustomNavbar";
import Profile from "@/app/components/Profile";
import { Inter } from "next/font/google";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DMM : Home",
  description: "Generated by create next app",
};

export default function Home({ children }) {
  return (
    <div>
      <div>
        <CustomNavbar />
        {children}
      </div>
    </div>
  );
}
